const ListItems = [
        {name:'Overview', index:0, url:'#overview'},
        {name:'Code', index:1 ,url:'#code'},
        {name:'Deployed Contracts', index:2,url:'#deployedContracts'},
        {name:'Process', index:3,url:'#process'},
        {name:'Glossary', index:4,url:'#glossary'},
        {name:'Governance Reference', index:5,url:'#governanceReference'},
        {name:'BIT', index:6, url:'#bit'},
        {name:'Delegate', index:7, url:'#delegate'},
        {name:'Delegate By Signature ', index:8, url:'#delegateBySignature'},
        {name:'Get Current Votes', index:9, url:'#getCurrentVotes'},
        {name:'Get Prior Votes ', index:10, url:'#getPriorVotes'},
        {name:'Key Events', index:11, url:'#keyEvents'},
        {name:'Governor Bravo', index:12, url:'#governorBravo'},
        {name:'Quorum Votes', index:13, url:'#quorumVotes'},
        {name:'Proposal Threshold ', index:14, url:'#proposalThreshold'},
        {name:'Proposal Max Operations ', index:15, url:'#proposalMaxOperations'},
        {name:'Voting Delay', index:16, url:'#votingDelay'},
        {name:'Voting Period', index:17, url:'#votingPeriod'},
        {name:'Propose', index:18, url:'p#ropose'},
        {name:'Queue', index:19, url:'#queue'},
        {name:'Execute', index:20, url:'#execute'},
        {name:'Cancel', index:21, url:'#cancel'},
        {name:'Get Actions', index:22, url:'#getActions'},
        {name:'Get Receipt', index:23, url:'#getReceipt'},
        {name:'State', index:24, url:'#state'},
        {name:'Cast Vote', index:25, url:'#castVote'},
        {name:'Cast Vote With Reason', index:26, url:'#castVoteWithReason'},
        {name:'Cast Vote By Signature', index:27, url:'#castVoteBySignature'},
        {name:'Timelock', index:28, url:'#timelock'},
        {name:'Pause Guardian', index:29, url:'#pauseGuardian'},

]


export default ListItems